In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cpu'

In [2]:
%config Completer.use_jedi = False # 자동완성 켜기

In [4]:
# 초기화 되지 않은 텐서
x = torch.empty(4,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
# 무작위로 초기화된 텐서
x = torch.rand(4,2)
x

tensor([[0.0168, 0.5030],
        [0.6730, 0.8864],
        [0.3727, 0.1743],
        [0.5763, 0.1148]])

In [6]:
# 사용자가 입력된 값으로 텐서 초기화
x = torch.tensor([3, 2.3])
x

tensor([3.0000, 2.3000])

In [7]:
# 2*4 크기,double type, 1로 채워진 텐서
x = x.new_ones(2,4,dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [8]:
# x(2*4)와 같은 크기, float type, 무작위로 채워진 텐서
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.3364,  0.4736,  0.7121,  0.4845],
        [-0.6146,  0.5763,  1.1034, -1.2444]])

In [9]:
# 텐서 크기계산
x.size()

torch.Size([2, 4])

In [10]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [11]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [13]:
# CUDA tensor

x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

tensor([1.0238])
1.0238337516784668
torch.float32
cpu
tensor([1.])
tensor([1.0238])
tensor([2.0238])
tensor([2.0238], dtype=torch.float64)


In [17]:
# 0D tensor

t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [18]:
# 1D tensor

t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [20]:
# 2D tensor

t2 = torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [22]:
# 3D tensor

t3 = torch.tensor([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [25]:
# tensor의 연산

import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.clamp(a,-0.5,0.5)) # clamp : 최대 또는 최소를 경계값으로 설정하여 최대보다 크거나 최소보다 작으면 최대 및 최소를 출력

tensor([[-0.8813,  0.8869]])
tensor([[0.8813, 0.8869]])
tensor([[-0., 1.]])
tensor([[-0.5000,  0.5000]])


In [26]:
# max, min

x = torch.rand(2,2)
print(x)
# dim을 설정해 차원을 설정할 수 있음
print(x.max(dim=0))
print(x.max(dim=1))

# min도 동일한 방법으로 !

tensor([[0.4626, 0.7332],
        [0.0224, 0.1630]])
torch.return_types.max(
values=tensor([0.4626, 0.7332]),
indices=tensor([0, 0]))
torch.return_types.max(
values=tensor([0.7332, 0.1630]),
indices=tensor([1, 1]))


In [27]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

# 둘 다 동일한 값 출력
print(x+y)
print(torch.add(x,y))

# add 덧셈, sub 뺄셈, mul 곱셉, div 나눗셈, matmul(mm) 내적, usv 분해

tensor([[0.2698, 0.6534],
        [0.6303, 0.6301]])
tensor([[0.3531, 0.6071],
        [0.6447, 0.5949]])
tensor([[0.6229, 1.2605],
        [1.2750, 1.2250]])
tensor([[0.6229, 1.2605],
        [1.2750, 1.2250]])


In [30]:
res = torch.empty(2,2)
print(res)
torch.add(x,y, out=res)
print(res)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.6229, 1.2605],
        [1.2750, 1.2250]])


In [31]:
# in-place

print(x)
print(y)
y.add_(x) # x+y 값을 y로 할당
print(y)

tensor([[0.2698, 0.6534],
        [0.6303, 0.6301]])
tensor([[0.3531, 0.6071],
        [0.6447, 0.5949]])
tensor([[0.6229, 1.2605],
        [1.2750, 1.2250]])


In [35]:
# indexing

x = torch.tensor([[1,2],
                  [3,4]])

print(x)
print(x[0,0])
print(x[0,1])

print(x[:,0])
print(x[:,1])
print(x[0,:])

tensor([[1, 2],
        [3, 4]])
tensor(1)
tensor(2)
tensor([1, 3])
tensor([2, 4])
tensor([1, 2])


In [38]:
# view : size나 shape 변경

x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5,-1)
print(z)

tensor([[-0.6596,  1.4578, -0.7411, -0.2691, -0.8357],
        [-0.1034,  1.4696, -0.9514, -0.5466, -0.8094],
        [ 0.8336,  1.1207,  0.4057,  0.8865, -0.6195],
        [-1.4376, -0.4371, -0.8817, -0.9100, -0.2228]])
tensor([-0.6596,  1.4578, -0.7411, -0.2691, -0.8357, -0.1034,  1.4696, -0.9514,
        -0.5466, -0.8094,  0.8336,  1.1207,  0.4057,  0.8865, -0.6195, -1.4376,
        -0.4371, -0.8817, -0.9100, -0.2228])
tensor([[-0.6596,  1.4578, -0.7411, -0.2691],
        [-0.8357, -0.1034,  1.4696, -0.9514],
        [-0.5466, -0.8094,  0.8336,  1.1207],
        [ 0.4057,  0.8865, -0.6195, -1.4376],
        [-0.4371, -0.8817, -0.9100, -0.2228]])


In [39]:
# item : 텐서에 값이 하나라도 있으면 숫자값을 얻을 수 있다.

x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.1052])
0.10521186143159866
torch.float32


In [44]:
# squeeze : 차원 축소

tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)
t = tensor.squeeze()
print(t)
print(t.shape)

# unsqueeze : 차원 증가
ten = torch.rand(3,3)
print(ten)
print(ten.shape)
ten = ten.unsqueeze(dim=2)
print(ten)
print(ten.shape)

tensor([[[0.8602, 0.8224, 0.8700],
         [0.0310, 0.7854, 0.2916],
         [0.6212, 0.4339, 0.4862]]])
torch.Size([1, 3, 3])
tensor([[0.8602, 0.8224, 0.8700],
        [0.0310, 0.7854, 0.2916],
        [0.6212, 0.4339, 0.4862]])
torch.Size([3, 3])
tensor([[0.8084, 0.8085, 0.6927],
        [0.9583, 0.4676, 0.5876],
        [0.3907, 0.7812, 0.6143]])
torch.Size([3, 3])
tensor([[[0.8084],
         [0.8085],
         [0.6927]],

        [[0.9583],
         [0.4676],
         [0.5876]],

        [[0.3907],
         [0.7812],
         [0.6143]]])
torch.Size([3, 3, 1])


In [45]:
# stack : 텐서 결합

x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [56]:
# cat : 텐서 결합(dim을 설정해야함)

a = torch.randn(1,3,3)
print(a)
b = torch.randn(1,3,3)
print(b)
c1 = torch.cat((a,b),dim=0)
c2 = torch.cat((a,b),dim=1)
c3 = torch.cat((a,b),dim=2)

print(c1.size())
print(c2.size())
print(c3.size())

tensor([[[ 0.7314,  1.1587,  0.5524],
         [ 0.2762,  0.2411, -0.6400],
         [ 0.4087, -0.2821,  0.9297]]])
tensor([[[ 1.6334, -0.4936, -1.9466],
         [ 0.9251,  1.3013, -1.1436],
         [-0.8161, -1.0045,  0.0428]]])
torch.Size([2, 3, 3])
torch.Size([1, 6, 3])
torch.Size([1, 3, 6])


In [65]:
# chunk : 텐서를 여러개로 나눌 때

ten = torch.rand(3,6)
print(ten)

t1, t2, t3 = torch.chunk(ten, 3, dim=1) # dim = 1 열 기준, dim = 0 행 기준
print(t1)
print(t2)
print(t3)

tensor([[0.9483, 0.8525, 0.0526, 0.7110, 0.2801, 0.8943],
        [0.4633, 0.6677, 0.9582, 0.8726, 0.4438, 0.8384],
        [0.7505, 0.3462, 0.6856, 0.0987, 0.3512, 0.7297]])
tensor([[0.9483, 0.8525],
        [0.4633, 0.6677],
        [0.7505, 0.3462]])
tensor([[0.0526, 0.7110],
        [0.9582, 0.8726],
        [0.6856, 0.0987]])
tensor([[0.2801, 0.8943],
        [0.4438, 0.8384],
        [0.3512, 0.7297]])


In [64]:
# split : chunk와 동일하지만 기능이 조금 다름

t1, t2 = torch.split(ten,3,dim=1)

print(t1)
print(t2)

tensor([[0.2018, 0.3259, 0.8006],
        [0.2115, 0.1484, 0.1155],
        [0.6270, 0.6980, 0.1226]])
tensor([[0.9474, 0.7873, 0.9717],
        [0.7990, 0.1702, 0.6796],
        [0.3738, 0.3272, 0.6515]])


In [68]:
# torch -> numpy

a = torch.ones(7)
print(a)
b = a.numpy()
print(b)

import numpy as np
a = np.ones(7)
print(a)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [72]:
# requires_grad : 텐서에서 이루어지는 연산 추적

a = torch.randn(3,3)
a = a * 3
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

b = (a*a).sum()
print(b)
print(b.grad_fn) # 미분값을 계산한 함수에 대한 정보 저장

tensor([[-7.2135, -0.2485, -1.0695],
        [-3.5586, -0.3858,  3.5931],
        [-0.8760,  3.6644, -1.1055]])
False
True
tensor(94.3808, grad_fn=<SumBackward0>)


In [86]:
# gradient : 기울기

x = torch.ones(3,3,requires_grad=True)
print(x)

y = x + 5
print(y)

z = y*y
out = z.mean()
print(z,out)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)
<bound method Tensor.backward of tensor(36., grad_fn=<MeanBackward0>)>


In [91]:
print(out)
out.backward() # 계산이 완료된 후 backward를 호출하면 자동으로 역전파 계산

tensor(36., grad_fn=<MeanBackward0>)


In [93]:
# 자동 미분

print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [104]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([ -150.4620, -1007.3784,   509.6524], grad_fn=<MulBackward0>)


In [105]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [107]:
a = torch.ones(2,2,requires_grad=True)
print(a)

print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
None
None


In [108]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [109]:
c = b ** 2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [110]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [111]:
out.backward()

In [112]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [113]:
print(b.data)
print(b.grad)
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
None


<ipython-input-113-7222c1aec66c>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:485.)
  print(b.grad)


In [114]:
print(c.data)
print(c.grad)
print(c.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


<ipython-input-114-f6ca42a4f63f>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:485.)
  print(c.grad)


In [1]:
import torch
import torch.nn as nn

In [26]:
x = torch.FloatTensor([[1],[2],[3]])
y = torch.FloatTensor([[1],[2],[3]])

w = torch.zeros(1,requires_grad=True)
opt = torch.optim.SGD([w], lr=0.15)

for i in range(10):
    hypo = x * w
    cost = torch.mean((hypo - y)**2)
    print(w.item(),cost.item())
    
    opt.zero_grad()
    cost.backward()
    opt.step()


0.0 4.666666507720947
1.4000000953674316 0.7466669678688049
0.8399999141693115 0.11946680396795273
1.0640000104904175 0.0191146582365036
0.9744000434875488 0.00305833644233644
1.0102399587631226 0.0004893290461041033
0.9959040284156799 7.829209789633751e-05
1.001638412475586 1.2527179023891222e-05
0.9993446469306946 2.0041973129991675e-06
1.0002621412277222 3.206215808404522e-07


In [4]:
## 다중선형회귀
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

w = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

opt = torch.optim.SGD([w,b], lr=1e-5)

nb_epoch = 20
for epoch in range(nb_epoch + 1):
    hypo = x_train.matmul(w) + b
    cost = torch.mean((hypo - y_train) ** 2)
    
    opt.zero_grad()
    cost.backward()
    opt.step()
    
    print('Epoch {:4d}/{} hypo : {} Cost: {:.6f}'.format(epoch, nb_epoch, hypo.squeeze().detach(),cost.item()))

Epoch    0/20 hypo : tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypo : tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypo : tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712891
Epoch    3/20 hypo : tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypo : tensor([137.7968, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936005
Epoch    5/20 hypo : tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371010
Epoch    6/20 hypo : tensor([148.1035, 178.0144, 175.3980, 191.0042, 135.7812]) Cost: 29.758139
Epoch    7/20 hypo : tensor([150.1744, 180.5042, 177.8508, 193.6753, 137.6805]) Cost: 10.445305
Epoch    8/20 hypo : tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391228
Epoch    9/20 hypo : tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493135
Epoch   10/20 hypo : tensor([152.3454, 183.1161, 180.4231, 196.4765,

In [8]:
## class를 이용한 다중선형회귀

import torch.nn as nn
import torch.nn.functional as F

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
    def forward(self, x):
        return self.linear(x)

x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])
    
model=MultivariateLinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)
nb_epochs=20

for epoch in range(nb_epochs+1):
    Hypothesis=model(x_train)
    cost=F.mse_loss(Hypothesis,y_train)
    optimizer.zero_grad()
    
    cost.backward()
    optimizer.step()
    print('Epoch {:4d}/{} Hypothesis: {}, Cost: {:.6f}'.format(epoch,nb_epochs,Hypothesis.squeeze().detach(),cost.item()))


Epoch    0/20 Hypothesis: tensor([ 82.6492, 101.8116,  99.0427, 107.8335,  78.2917]), Cost: 6023.204102
Epoch    1/20 Hypothesis: tensor([112.9574, 138.2399, 134.9361, 146.9205, 106.0774]), Cost: 1888.163086
Epoch    2/20 Hypothesis: tensor([129.9259, 158.6349, 155.0315, 168.8039, 121.6336]), Cost: 592.046692
Epoch    3/20 Hypothesis: tensor([139.4259, 170.0533, 166.2822, 181.0556, 130.3430]), Cost: 185.783051
Epoch    4/20 Hypothesis: tensor([144.7445, 176.4460, 172.5810, 187.9148, 135.2191]), Cost: 58.441231
Epoch    5/20 Hypothesis: tensor([147.7222, 180.0251, 176.1075, 191.7551, 137.9491]), Cost: 18.526140
Epoch    6/20 Hypothesis: tensor([149.3893, 182.0289, 178.0818, 193.9051, 139.4775]), Cost: 6.014852
Epoch    7/20 Hypothesis: tensor([150.3226, 183.1508, 179.1872, 195.1087, 140.3333]), Cost: 2.093277
Epoch    8/20 Hypothesis: tensor([150.8451, 183.7789, 179.8060, 195.7826, 140.8124]), Cost: 0.864031
Epoch    9/20 Hypothesis: tensor([151.1376, 184.1306, 180.1525, 196.1599, 141.0

In [28]:
from torch.utils.data import Dataset
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

class customdataset(Dataset):
    def __init__(self):
        self.x_data = [[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]]
        self.y_data = [[152],[185],[180],[196],[142]]
        
    def __len__(self):
        return len(self.x_data)
    
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        
        return x,y
    
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)

dataset = customdataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        
        Hypothesis=model(x_train)
        cost=F.mse_loss(Hypothesis,y_train)
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        print('Epoch {:4d}/{} batch: {}/{}, Cost: {:.6f}'.format(epoch,nb_epochs,batch_idx + 1,len(dataloader),cost.item()))


Epoch    0/20 batch: 1/3, Cost: 34509.062500
Epoch    0/20 batch: 2/3, Cost: 8378.459961
Epoch    0/20 batch: 3/3, Cost: 4043.194824
Epoch    1/20 batch: 1/3, Cost: 985.153625
Epoch    1/20 batch: 2/3, Cost: 186.964783
Epoch    1/20 batch: 3/3, Cost: 118.014198
Epoch    2/20 batch: 1/3, Cost: 18.098715
Epoch    2/20 batch: 2/3, Cost: 11.047340
Epoch    2/20 batch: 3/3, Cost: 1.249609
Epoch    3/20 batch: 1/3, Cost: 2.205516
Epoch    3/20 batch: 2/3, Cost: 0.084831
Epoch    3/20 batch: 3/3, Cost: 0.156028
Epoch    4/20 batch: 1/3, Cost: 1.048458
Epoch    4/20 batch: 2/3, Cost: 0.332785
Epoch    4/20 batch: 3/3, Cost: 0.051705
Epoch    5/20 batch: 1/3, Cost: 1.037663
Epoch    5/20 batch: 2/3, Cost: 0.287627
Epoch    5/20 batch: 3/3, Cost: 0.001999
Epoch    6/20 batch: 1/3, Cost: 0.911425
Epoch    6/20 batch: 2/3, Cost: 0.390446
Epoch    6/20 batch: 3/3, Cost: 0.069177
Epoch    7/20 batch: 1/3, Cost: 1.042158
Epoch    7/20 batch: 2/3, Cost: 0.394659
Epoch    7/20 batch: 3/3, Cost: 0.03629